services:
  proxy:
    image: ghcr.io/llstudent83/proxy-services-priguli:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    networks:
      - priguli-apps  # Подключение к внешней сети
    restart: unless-stopped

networks:
  priguli-apps:
    external: true